# INFS770
## Assignment 3
### Kevin Kuipers 
#### 04/07/2020

### Text data preprocessing and topic modeling

# T1
##### I will begin by downloading the nltk package. This will be used for the bag of words method. The text file that will be used consists of text. Each line represents a single review. The nltk package is commented it but if needed please feel free to uncomment to download the package. The first step in this process is writing code to create a list of strings from the review.txt file. After imported, the list will be outputted. 

In [1]:
#downloading the nlkt library
import nltk
#nltk.download()

In [2]:
#Loading other libraries that will be used later on
import numpy as np
import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer

In [3]:
#importing the file
with open('reviews.txt') as f:
    docs = f.readlines()
#outputting the list
docs

['with all the available applications and new updates for its software , iphone is a phone you grow with , not out of .\n',
 'i upgraded from the sd550 canon there is not comparisent .\n',
 'i have also converted my office from the pc and windows world to mac os and that is the best business decision i have made in years i have tried other phones with android , windows mobile and they all fall short  .\n',
 "i've also experienced the unit occasionally freezing or resetting itself , usually when the bluetooth connection is active and i'm receiving a phone call  .\n",
 "this is my family's seventh (at least) garmin unit , and may be our last .\n",
 'thanks canon for making my family happy and able to share our family photos again  .\n',
 'a really great camera  .\n',
 'so i knew when i is buying this unit i is not buying a unit that i would build for this price but the best available as far as it being balanced in   , efficientcy and bells and whisles  .\n',
 '(i have one , and i will al

In [4]:
#printing the list using the print method
print(docs)

['with all the available applications and new updates for its software , iphone is a phone you grow with , not out of .\n', 'i upgraded from the sd550 canon there is not comparisent .\n', 'i have also converted my office from the pc and windows world to mac os and that is the best business decision i have made in years i have tried other phones with android , windows mobile and they all fall short  .\n', "i've also experienced the unit occasionally freezing or resetting itself , usually when the bluetooth connection is active and i'm receiving a phone call  .\n", "this is my family's seventh (at least) garmin unit , and may be our last .\n", 'thanks canon for making my family happy and able to share our family photos again  .\n', 'a really great camera  .\n', 'so i knew when i is buying this unit i is not buying a unit that i would build for this price but the best available as far as it being balanced in   , efficientcy and bells and whisles  .\n', '(i have one , and i will also be ge

# T2

##### Now I will write code to tokenize the docs using the TF-IDF vectorizer. Doing so I will do the following steps:
##### 1) Remove punctuations
##### 2) Remove numbers
##### 3) Do a lemmatization
##### 4) Remove stop words
##### 5) Remove words that appear in only one document
##### 6) Remove words that appears in over 90% of the documents
##### 7) Print the features extracted based on the TF-IDF 

#### Removal punctuations and numbers

In [5]:
#1 Remove Punctuations
#2 Remove numbers
# I will also convert all words to lower case

def remove(docus):
    #convert words to lower case
    lower_c = map(str.lower, docus)
    
    #1. remove punctuations
    remove_punc = list(map(lambda x: " ".join(re.findall('\\b\\w\\w+\\b',x)),lower_c))
    
    #2. remove numbers
    return list(map(lambda x:re.sub('\\b[0-9]+\\b', '', x), remove_punc))

docs = remove(docs)
print(docs)

['with all the available applications and new updates for its software iphone is phone you grow with not out of', 'upgraded from the sd550 canon there is not comparisent', 'have also converted my office from the pc and windows world to mac os and that is the best business decision have made in years have tried other phones with android windows mobile and they all fall short', 've also experienced the unit occasionally freezing or resetting itself usually when the bluetooth connection is active and receiving phone call', 'this is my family seventh at least garmin unit and may be our last', 'thanks canon for making my family happy and able to share our family photos again', 'really great camera', 'so knew when is buying this unit is not buying unit that would build for this price but the best available as far as it being balanced in efficientcy and bells and whisles', 'have one and will also be getting the iphone 4g as soon as it comes out as well it is by far the best mobile that is cur

### Lemmatization

##### In the block below I will do lemmatization and in the process of doing this I will also remove stop words and removes words that appear in only one document and words that appear in over 90% of the document. 

In [6]:
from nltk import word_tokenize
from nltk.stem import WordNetLemmatizer

#3 lemmatization 
class LemmaTokenizer(object):
    def __init__(self):
        self.wnl = WordNetLemmatizer()
    def __call__(self, doc):
        return [self.wnl.lemmatize(t, 'v') for t in word_tokenize(doc)]
#3 lemmatization
#4 remove stop words
#5 remove words that only appear in only one document
#6 Remove words that appear in over 90% of the documents
vectorizer_norm = TfidfVectorizer(tokenizer=LemmaTokenizer(), lowercase=True, stop_words = 'english', 
                            max_df=.90, min_df=2,norm=None)
X_norm = vectorizer_norm.fit_transform(docs)
df_tf_norm = pd.DataFrame(X_norm.todense(), columns=vectorizer_norm.get_feature_names())

print(X_norm)
print(df_tf_norm)

C:\Users\Agent000\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['make'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


  (0, 20)	5.3652195163575005
  (0, 16)	5.3652195163575005
  (0, 163)	4.384390263345774
  (0, 269)	4.85439389259151
  (0, 239)	5.07753744390572
  (0, 130)	2.96732424355913
  (0, 182)	3.029844600540464
  (0, 114)	5.3652195163575005
  (1, 270)	5.3652195163575005
  (1, 222)	5.3652195163575005
  (1, 41)	4.161246712031565
  (2, 182)	3.029844600540464
  (2, 178)	5.3652195163575005
  (2, 283)	4.672072335797555
  (2, 27)	4.065936532227239
  (2, 36)	5.07753744390572
  (2, 149)	4.161246712031565
  (2, 286)	5.07753744390572
  (2, 265)	5.3652195163575005
  (2, 12)	5.3652195163575005
  (2, 154)	5.3652195163575005
  (3, 182)	3.029844600540464
  (3, 276)	3.9789251552376097
  (3, 90)	4.384390263345774
  (3, 267)	3.8247744754103516
  :	:
  (229, 231)	4.517921655970296
  (230, 130)	2.96732424355913
  (230, 257)	4.517921655970296
  (230, 28)	4.517921655970296
  (230, 248)	4.85439389259151
  (231, 182)	3.029844600540464
  (231, 149)	4.161246712031565
  (231, 272)	3.029844600540464
  (231, 132)	3.8247744754

### Printing the features (i.e., vectorizer.vocabulary_) extracted based on TF-IDF

In [7]:
vectorizer_norm.vocabulary_

{'available': 20,
 'applications': 16,
 'new': 163,
 'update': 269,
 'software': 239,
 'iphone': 130,
 'phone': 182,
 'grow': 114,
 'upgrade': 270,
 'sd550': 222,
 'canon': 41,
 'pc': 178,
 'world': 283,
 'best': 27,
 'business': 36,
 'make': 149,
 'years': 286,
 'try': 265,
 'android': 12,
 'mobile': 154,
 've': 276,
 'experience': 90,
 'unit': 267,
 'freeze': 104,
 'reset': 211,
 'usually': 275,
 'bluetooth': 32,
 'receive': 207,
 'family': 92,
 'garmin': 107,
 'thank': 253,
 'happy': 117,
 'able': 1,
 'share': 230,
 'photos': 185,
 'really': 205,
 'great': 113,
 'camera': 39,
 'know': 133,
 'buy': 37,
 'build': 35,
 'price': 194,
 'far': 94,
 'balance': 25,
 'currently': 71,
 'offer': 170,
 'carry': 46,
 'month': 157,
 'data': 72,
 'plan': 189,
 'way': 279,
 'blackberry': 30,
 'digital': 78,
 'time': 257,
 'couldn': 66,
 'sd790is': 225,
 'easy': 87,
 'auto': 19,
 'mode': 155,
 'want': 278,
 'users': 274,
 'multitasking': 160,
 'big': 29,
 'deal': 73,
 'smart': 238,
 'tiny': 258,
 'h

# T3

# TF-IDF

##### TF-IDF stands for term frequency (TF) and inverse document frequency (IDF). TF-IDF is an information retrieval technique that incorporates the term frequency the ineverse document frequency to produce a weight or score. In some sense, the score represents the occurance of each word; a lower score means the word/term is recurrent, the higher a score the word/term is scarce.   The term frequency (TF) is the number of times the word appears in a document. The inverse document frequency (IDF) measures the signficance of the word/term in a entire corpus. 

##### Lets break this down a littlle further. If the word "data" appears 100 times in 1,000 word document the TF would be the 10/1000 = 0.10. This means the term frequency is 10% in that 1000 word document. 

# T4

##### Next I will build a topic odle using Latent Dirichlet Allocation (LDA) and the vectorized data obtained from T2. In this build I will se the number of topics to 3 and print the the topics.

In [8]:
import gensim
import pandas as pd
import numpy as np
from gensim.models import LdaModel, LsiModel
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim import corpora
from gensim.corpora import Dictionary
from gensim import *

In [9]:
corpus_norm = gensim.matutils.Sparse2Corpus(X_norm, documents_columns=False)
id2word_norm = dict((v,k) for k,v in vectorizer_norm.vocabulary_.items())
id2word_norm

{20: 'available',
 16: 'applications',
 163: 'new',
 269: 'update',
 239: 'software',
 130: 'iphone',
 182: 'phone',
 114: 'grow',
 270: 'upgrade',
 222: 'sd550',
 41: 'canon',
 178: 'pc',
 283: 'world',
 27: 'best',
 36: 'business',
 149: 'make',
 286: 'years',
 265: 'try',
 12: 'android',
 154: 'mobile',
 276: 've',
 90: 'experience',
 267: 'unit',
 104: 'freeze',
 211: 'reset',
 275: 'usually',
 32: 'bluetooth',
 207: 'receive',
 92: 'family',
 107: 'garmin',
 253: 'thank',
 117: 'happy',
 1: 'able',
 230: 'share',
 185: 'photos',
 205: 'really',
 113: 'great',
 39: 'camera',
 133: 'know',
 37: 'buy',
 35: 'build',
 194: 'price',
 94: 'far',
 25: 'balance',
 71: 'currently',
 170: 'offer',
 46: 'carry',
 157: 'month',
 72: 'data',
 189: 'plan',
 279: 'way',
 30: 'blackberry',
 78: 'digital',
 257: 'time',
 66: 'couldn',
 225: 'sd790is',
 87: 'easy',
 19: 'auto',
 155: 'mode',
 278: 'want',
 274: 'users',
 160: 'multitasking',
 29: 'big',
 73: 'deal',
 238: 'smart',
 258: 'tiny',
 12

# T4 LDA with 3 topics

In [10]:
lda_norm_t3 = LdaModel(corpus_norm, num_topics = 3, id2word=id2word_norm, passes=1000, random_state=712)
lda_norm_t3.print_topics()

[(0,
  '0.053*"phone" + 0.042*"iphone" + 0.020*"best" + 0.019*"apps" + 0.018*"know" + 0.017*"use" + 0.015*"apple" + 0.015*"better" + 0.014*"experience" + 0.013*"make"'),
 (1,
  '0.045*"camera" + 0.034*"great" + 0.027*"picture" + 0.020*"buy" + 0.020*"easy" + 0.018*"like" + 0.017*"use" + 0.017*"far" + 0.016*"battery" + 0.015*"sd790is"'),
 (2,
  '0.029*"traffic" + 0.022*"garmin" + 0.019*"happy" + 0.019*"way" + 0.019*"love" + 0.016*"google" + 0.016*"use" + 0.015*"iphone" + 0.014*"family" + 0.014*"device"')]

# T5 LDA with 4 Topics

In [11]:
lda_norm_t4 = LdaModel(corpus_norm, num_topics = 4, id2word=id2word_norm, passes=1000, random_state=712)
lda_norm_t4.print_topics()

[(0,
  '0.062*"phone" + 0.043*"iphone" + 0.022*"apps" + 0.017*"say" + 0.017*"better" + 0.017*"apple" + 0.017*"use" + 0.015*"rout" + 0.014*"experience" + 0.013*"carrier"'),
 (1,
  '0.049*"camera" + 0.048*"great" + 0.038*"picture" + 0.026*"like" + 0.021*"big" + 0.021*"use" + 0.019*"point" + 0.019*"quality" + 0.017*"easy" + 0.017*"shoot"'),
 (2,
  '0.023*"iphone" + 0.022*"price" + 0.020*"use" + 0.019*"family" + 0.018*"lot" + 0.018*"google" + 0.018*"way" + 0.017*"highway" + 0.017*"recommend" + 0.016*"garmin"'),
 (3,
  '0.033*"traffic" + 0.025*"unit" + 0.020*"know" + 0.019*"garmin" + 0.019*"new" + 0.018*"sd790is" + 0.018*"screen" + 0.017*"device" + 0.017*"camera" + 0.016*"service"')]

# T6 LDA with 5 Topics

In [12]:
lda_norm_t5 = LdaModel(corpus_norm, num_topics = 5, id2word=id2word_norm, passes=1000, random_state=712)
lda_norm_t5.print_topics()

[(0,
  '0.071*"phone" + 0.053*"iphone" + 0.030*"apps" + 0.028*"use" + 0.023*"better" + 0.021*"experience" + 0.020*"rout" + 0.020*"world" + 0.018*"know" + 0.017*"switch"'),
 (1,
  '0.060*"great" + 0.053*"picture" + 0.048*"camera" + 0.040*"easy" + 0.033*"use" + 0.027*"point" + 0.024*"shoot" + 0.022*"like" + 0.020*"quality" + 0.019*"really"'),
 (2,
  '0.022*"iphone" + 0.020*"price" + 0.018*"family" + 0.018*"use" + 0.018*"google" + 0.018*"lot" + 0.016*"recommend" + 0.016*"make" + 0.016*"need" + 0.015*"start"'),
 (3,
  '0.031*"traffic" + 0.024*"just" + 0.023*"screen" + 0.021*"think" + 0.021*"video" + 0.021*"camera" + 0.020*"device" + 0.019*"work" + 0.018*"love" + 0.017*"happy"'),
 (4,
  '0.027*"battery" + 0.027*"life" + 0.026*"say" + 0.026*"buy" + 0.024*"like" + 0.024*"don" + 0.023*"garmin" + 0.022*"highway" + 0.019*"way" + 0.018*"route"')]

# T7

##### It seems 3 topics makes the most sense above.
##### Topic 1 - IPhone Reviews ---- keywords like "Iphone, phone, apple, apps"
##### Topic 2 - Camera Reviews (particularly picture quality and battery life) ---- keywords like  "camera, picture, quality, screen, battery, life"
##### Topic 3 - Garmin Device Reviews ---- keywords like "garmin, traffic, device"

##### With 3 topics some words do not help in identifying a topic like 'know', 'way', 'like', 'use'. However, words like this tend to occur more frequently when increasing the number topics in this corpus. Therefore, I think 3 topics makese the most sense based on the results above.    

# T8
##### Re-running the TF-IDF vectorizeor with the norm to be set to 'l1'. Then fit a LdaModel with with the optimal results I received above. In this case, the LdaModel will consist of 3 topics.

In [13]:
vectorizer_l1 = TfidfVectorizer(tokenizer=LemmaTokenizer(), lowercase=True, stop_words = 'english', 
                            max_df=.90, min_df=2,norm='l1')
X_l1 = vectorizer_l1.fit_transform(docs)
df_tf_l1 = pd.DataFrame(X_l1.todense(), columns=vectorizer_l1.get_feature_names())
#print(X_l1)
#print(df_tf_l1)

corpus_l1 = gensim.matutils.Sparse2Corpus(X_l1, documents_columns=False)
id2word_l1 = dict((v,k) for k,v in vectorizer_l1.vocabulary_.items())
#id2word_l1

lda_l1_t3 = LdaModel(corpus_l1, num_topics = 3, id2word=id2word_l1, passes=1000, random_state=712)
lda_l1_t3.print_topics()

C:\Users\Agent000\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['make'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


[(0,
  '0.046*"iphone" + 0.031*"phone" + 0.018*"know" + 0.013*"best" + 0.013*"ve" + 0.013*"just" + 0.013*"use" + 0.012*"better" + 0.011*"route" + 0.011*"mom"'),
 (1,
  '0.033*"great" + 0.028*"camera" + 0.023*"picture" + 0.018*"use" + 0.015*"easy" + 0.015*"like" + 0.013*"garmins" + 0.013*"canon" + 0.012*"point" + 0.011*"shoot"'),
 (2,
  '0.024*"recommend" + 0.023*"happy" + 0.016*"love" + 0.015*"garmin" + 0.013*"traffic" + 0.012*"guess" + 0.011*"unit" + 0.010*"new" + 0.009*"data" + 0.009*"screen"')]

##### Using the same number of topics but switching the vectorizer to norm='l1' does not seem to produce the exact same results as previously seen. Topic 2 has the word 'garmins' in it which I do not like because I classified topic 2 to camera. Overall, I think the results enough similar to stay the same classified topics that I used when using the norm approach. 

# T9
##### Re-running the TF-IDF vectorizeor with the norm to be set to 'l2'. Then fit a LdaModel with with the optimal results I received above. In this case, the LdaModel will consist of 3 topics.

In [14]:
vectorizer_l2 = TfidfVectorizer(tokenizer=LemmaTokenizer(), lowercase=True, stop_words = 'english', 
                            max_df=.90, min_df=2,norm='l2')
X_l2 = vectorizer_l2.fit_transform(docs)
df_tf_l2 = pd.DataFrame(X_l2.todense(), columns=vectorizer_l2.get_feature_names())
#print(X_l2)
#print(df_tf_l2)

corpus_l2 = gensim.matutils.Sparse2Corpus(X_l2, documents_columns=False)
id2word_l2 = dict((v,k) for k,v in vectorizer_l2.vocabulary_.items())
#id2word_l2

lda_l2_t3 = LdaModel(corpus_l2, num_topics = 3, id2word=id2word_l2, passes=1000, random_state=712)
lda_l2_t3.print_topics()

[(0,
  '0.052*"iphone" + 0.042*"phone" + 0.020*"know" + 0.015*"use" + 0.015*"apps" + 0.014*"better" + 0.011*"ve" + 0.011*"think" + 0.011*"experience" + 0.010*"app"'),
 (1,
  '0.035*"camera" + 0.034*"great" + 0.023*"use" + 0.023*"picture" + 0.017*"easy" + 0.016*"like" + 0.015*"buy" + 0.014*"canon" + 0.013*"point" + 0.012*"far"'),
 (2,
  '0.023*"recommend" + 0.023*"happy" + 0.021*"love" + 0.020*"garmin" + 0.018*"traffic" + 0.016*"unit" + 0.011*"amaze" + 0.011*"data" + 0.010*"service" + 0.010*"search"')]

# T10

## Norm=None w/3 Topics
###### [(0, '0.053*"phone" + 0.042*"iphone" + 0.020*"best" + 0.019*"apps" + 0.018*"know" + 0.017*"use" + 0.015*"apple" + 0.015*"better" + 0.014*"experience" + 0.013*"make"'),
###### (1,'0.045*"camera" + 0.034*"great" + 0.027*"picture" + 0.020*"buy" + 0.020*"easy" + 0.018*"like" + 0.017*"use" + 0.017*"far" + 0.016*"battery" + 0.015*"sd790is"'),
###### (2, '0.029*"traffic" + 0.022*"garmin" + 0.019*"happy" + 0.019*"way" + 0.019*"love" + 0.016*"google" + 0.016*"use" + 0.015*"iphone" + 0.014*"family" + 0.014*"device"')]

#### ---------------------------------------------------------------------------------------------------------------------------

## Norm='L1' w/3 Topics
###### [(0,'0.046*"iphone" + 0.031*"phone" + 0.018*"know" + 0.013*"best" + 0.013*"ve" + 0.013*"just" + 0.013*"use" + 0.012*"better" + 0.011*"route" + 0.011*"mom"'),
###### (1,'0.033*"great" + 0.028*"camera" + 0.023*"picture" + 0.018*"use" + 0.015*"easy" + 0.015*"like" + 0.013*"garmins" + 0.013*"canon" + 0.012*"point" + 0.011*"shoot"'),
###### (2,'0.024*"recommend" + 0.023*"happy" + 0.016*"love" + 0.015*"garmin" + 0.013*"traffic" + 0.012*"guess" + 0.011*"unit" + 0.010*"new" + 0.009*"data" + 0.009*"screen"')]

#### ---------------------------------------------------------------------------------------------------------------------------

## Norm='L2' w/3 Topics

###### [(0,'0.052*"iphone" + 0.042*"phone" + 0.020*"know" + 0.015*"use" + 0.015*"apps" + 0.014*"better" + 0.011*"ve" + 0.011*"think" + 0.011*"experience" + 0.010*"app"'),
###### (1,'0.035*"camera" + 0.034*"great" + 0.023*"use" + 0.023*"picture" + 0.017*"easy" + 0.016*"like" + 0.015*"buy" + 0.014*"canon" + 0.013*"point" + 0.012*"far"'),
###### (2,'0.023*"recommend" + 0.023*"happy" + 0.021*"love" + 0.020*"garmin" + 0.018*"traffic" + 0.016*"unit" + 0.011*"amaze" + 0.011*"data" + 0.010*"service" + 0.010*"search"')]


##### When comparing the 3 different LDA Model outputs of the topics, I think the LDA model with norm='L2' produces the optimal results.  The key words that it flags just help solidify my previous response and offer more clues to the topic. I think provides more clarity to the topic. For example, L2 - Topic 2 has the word 'canon' and that word with camera easily tells us that the topic has to do cameras. 'L1' does capture this but it also has the word 'garmins' in there and I think that should be in another topic all together. 

##### I also think L2 does the best job capturing key words for topic 3. Whereas, norm='None' flags iphone in there. And it is possible that people are referecing iphone when reviewing garmin but if we are to put label on it, I think the 'L2' does a better job because I think the topic should be something like 'garmin reviews'. 


##### Overall, I think the norm=None and L2 are very close in results but I think L2 produces a little better bit results. 

# T11

##### Now I will print the topic/document table of LDA model with the optimal results

In [15]:
print(X_l2)

  (0, 20)	0.4080149131342344
  (0, 16)	0.4080149131342344
  (0, 163)	0.33342468225048666
  (0, 269)	0.3691675795121568
  (0, 239)	0.386137229389175
  (0, 130)	0.22565946086374686
  (0, 182)	0.23041401712096757
  (0, 114)	0.4080149131342344
  (1, 270)	0.6199888618504085
  (1, 222)	0.6199888618504085
  (1, 41)	0.48086133381970947
  (2, 182)	0.1991074575922618
  (2, 178)	0.3525775602932807
  (2, 283)	0.3070271142955167
  (2, 27)	0.2671946559631652
  (2, 36)	0.33367241709533274
  (2, 149)	0.27345800279623894
  (2, 286)	0.33367241709533274
  (2, 265)	0.3525775602932807
  (2, 12)	0.3525775602932807
  (2, 154)	0.3525775602932807
  (3, 182)	0.21555530100017295
  (3, 276)	0.2830766994919179
  (3, 90)	0.3119231140597583
  (3, 267)	0.2721098016570854
  :	:
  (229, 231)	0.6479141931848891
  (230, 130)	0.3468399279607861
  (230, 257)	0.5280837188893434
  (230, 28)	0.5280837188893434
  (230, 248)	0.5674127563424696
  (231, 182)	0.20528758579377762
  (231, 149)	0.28194590945452225
  (231, 272)	0.2052

In [16]:
print(df_tf_l2)

           3g      able    access  account  accurate  actually   ad  addition  \
0    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
1    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
2    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
3    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
4    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
5    0.000000  0.303322  0.000000      0.0       0.0  0.000000  0.0       0.0   
6    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
7    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
8    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
9    0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
10   0.000000  0.000000  0.000000      0.0       0.0  0.000000  0.0       0.0   
11   0.000000  0.000000  0.0

In [17]:
lda_docs_l2 = lda_l2_t3[corpus_l2]
for row in lda_docs_l2:
    print(row)

[(0, 0.81191444), (1, 0.089110516), (2, 0.098975025)]
[(0, 0.12321146), (1, 0.75339836), (2, 0.123390146)]
[(0, 0.8287235), (1, 0.08453188), (2, 0.086744696)]
[(0, 0.82307935), (1, 0.08709618), (2, 0.08982447)]
[(0, 0.12501135), (1, 0.12278348), (2, 0.7522052)]
[(0, 0.09633774), (1, 0.15876813), (2, 0.7448941)]
[(0, 0.12351134), (1, 0.7529353), (2, 0.12355341)]
[(0, 0.36440864), (1, 0.5220867), (2, 0.11350467)]
[(0, 0.4540858), (1, 0.45231292), (2, 0.0936013)]
[(0, 0.20102604), (1, 0.100197695), (2, 0.69877625)]
[(0, 0.71811736), (1, 0.18164529), (2, 0.10023736)]
[(0, 0.46635345), (1, 0.42044666), (2, 0.11319987)]
[(0, 0.81585735), (1, 0.09374621), (2, 0.090396434)]
[(0, 0.09389543), (1, 0.8130665), (2, 0.09303807)]
[(0, 0.6808499), (1, 0.1787208), (2, 0.14042926)]
[(0, 0.7203153), (1, 0.1398087), (2, 0.13987605)]
[(0, 0.11195291), (1, 0.77582425), (2, 0.11222287)]
[(0, 0.53402096), (1, 0.34363946), (2, 0.12233962)]
[(0, 0.111239076), (1, 0.78190666), (2, 0.10685422)]
[(0, 0.83430624),

[(0, 0.10184383), (1, 0.48332193), (2, 0.41483423)]
[(0, 0.50849247), (1, 0.3978798), (2, 0.093627736)]
[(0, 0.10250252), (1, 0.7965437), (2, 0.100953735)]
[(0, 0.79919845), (1, 0.10215865), (2, 0.09864288)]
[(0, 0.123402245), (1, 0.75316834), (2, 0.12342939)]
[(0, 0.7735322), (1, 0.11253241), (2, 0.11393538)]
[(0, 0.7277683), (1, 0.09870393), (2, 0.17352776)]
[(0, 0.33333334), (1, 0.33333334), (2, 0.33333334)]
[(0, 0.08347169), (1, 0.422469), (2, 0.49405932)]
[(0, 0.14366508), (1, 0.6998942), (2, 0.15644075)]


In [18]:
scores =  np.round([[doc[1] for doc in row] for row in lda_docs_l2],3)
print(scores)

[[0.812 0.089 0.099]
 [0.123 0.753 0.123]
 [0.829 0.085 0.087]
 [0.823 0.087 0.09 ]
 [0.125 0.123 0.752]
 [0.096 0.159 0.745]
 [0.124 0.753 0.124]
 [0.364 0.522 0.114]
 [0.454 0.453 0.094]
 [0.201 0.1   0.699]
 [0.718 0.182 0.1  ]
 [0.466 0.42  0.113]
 [0.816 0.094 0.09 ]
 [0.094 0.813 0.093]
 [0.681 0.179 0.14 ]
 [0.72  0.14  0.14 ]
 [0.112 0.776 0.112]
 [0.534 0.344 0.122]
 [0.111 0.782 0.107]
 [0.834 0.084 0.082]
 [0.139 0.139 0.722]
 [0.139 0.722 0.139]
 [0.143 0.716 0.141]
 [0.167 0.665 0.168]
 [0.068 0.855 0.077]
 [0.754 0.123 0.123]
 [0.501 0.125 0.374]
 [0.118 0.777 0.105]
 [0.108 0.781 0.11 ]
 [0.114 0.774 0.112]
 [0.255 0.591 0.154]
 [0.11  0.114 0.777]
 [0.378 0.14  0.482]
 [0.752 0.124 0.124]
 [0.119 0.768 0.113]
 [0.739 0.124 0.136]
 [0.088 0.475 0.437]
 [0.099 0.1   0.801]
 [0.742 0.136 0.122]
 [0.384 0.123 0.493]
 [0.333 0.333 0.333]
 [0.823 0.088 0.09 ]
 [0.152 0.467 0.381]
 [0.463 0.114 0.422]
 [0.113 0.765 0.122]
 [0.666 0.167 0.167]
 [0.14  0.712 0.149]
 [0.104 0.509

In [19]:
df_lda_l2_conv = pd.DataFrame(scores, columns=['Topic 1', 'Topic 2', 'Topic 3'])
df_lda_l2_conv

Topic 1  Topic 2  Topic 3
0      0.812    0.089    0.099
1      0.123    0.753    0.123
2      0.829    0.085    0.087
3      0.823    0.087    0.090
4      0.125    0.123    0.752
5      0.096    0.159    0.745
6      0.124    0.753    0.124
7      0.364    0.522    0.114
8      0.454    0.453    0.094
9      0.201    0.100    0.699
10     0.718    0.182    0.100
11     0.466    0.420    0.113
12     0.816    0.094    0.090
13     0.094    0.813    0.093
14     0.681    0.179    0.140
15     0.720    0.140    0.140
16     0.112    0.776    0.112
17     0.534    0.344    0.122
18     0.111    0.782    0.107
19     0.834    0.084    0.082
20     0.139    0.139    0.722
21     0.139    0.722    0.139
22     0.143    0.716    0.141
23     0.167    0.665    0.168
24     0.068    0.855    0.077
25     0.754    0.123    0.123
26     0.501    0.125    0.374
27     0.118    0.777    0.105
28     0.108    0.781    0.110
29     0.114    0.774    0.112
..       ...      ...      ...
205    0.293    0.099    0.608
206    0.829    0.086    0.085
207    0.146    0.143    0.711
208    0.757    0.130    0.114
209    0.750    0.125    0.125
210    0.105    0.340    0.555
211    0.167    0.665    0.167
212    0.809    0.101    0.090
213    0.123    0.126    0.751
214    0.272    0.603    0.125
215    0.515    0.098    0.386
216    0.188    0.103    0.709
217    0.125    0.123    0.752
218    0.228    0.088    0.685
219    0.293    0.611    0.096
220    0.073    0.434    0.494
221    0.778    0.109    0.113
222    0.112    0.109    0.779
223    0.145    0.139    0.716
224    0.109    0.114    0.777
225    0.102    0.483    0.415
226    0.509    0.398    0.094
227    0.102    0.797    0.101
228    0.799    0.102    0.099
229    0.123    0.753    0.123
230    0.774    0.113    0.114
231    0.728    0.099    0.174
232    0.333    0.333    0.333
233    0.083    0.422    0.494
234    0.144    0.700    0.156

[235 rows x 3 columns]

# T12

##### Now I will run truncated SVD and will set the n_componets to the 3 to match the number of optimal topics. Lastly, I will print the topics and number of topics and the topic/document table

In [20]:
#SVD 

from scipy.linalg import svd
U, s, V = svd(X_l2.toarray())
print(s)

[3.03719662e+00 2.67496162e+00 2.24290736e+00 2.12715640e+00
 2.02701793e+00 2.00982572e+00 1.96161772e+00 1.89881521e+00
 1.89159490e+00 1.82520980e+00 1.76143523e+00 1.75004996e+00
 1.72511190e+00 1.69640930e+00 1.67526614e+00 1.65785968e+00
 1.64317415e+00 1.62102516e+00 1.60899590e+00 1.58805178e+00
 1.57980594e+00 1.55543550e+00 1.53597018e+00 1.52811708e+00
 1.51739758e+00 1.50814709e+00 1.48832680e+00 1.46878585e+00
 1.46231635e+00 1.44317730e+00 1.43602788e+00 1.43022637e+00
 1.40929984e+00 1.39558186e+00 1.38557455e+00 1.38239402e+00
 1.36397320e+00 1.35180521e+00 1.34854066e+00 1.33843191e+00
 1.32767374e+00 1.32011507e+00 1.30704037e+00 1.30043183e+00
 1.29263337e+00 1.27090282e+00 1.26363292e+00 1.25660351e+00
 1.24997537e+00 1.24251179e+00 1.23788057e+00 1.22843690e+00
 1.21527482e+00 1.20976506e+00 1.20720902e+00 1.19311386e+00
 1.18242997e+00 1.16961724e+00 1.16380648e+00 1.14910747e+00
 1.14585737e+00 1.13854195e+00 1.13262925e+00 1.12763513e+00
 1.12356595e+00 1.114401

In [21]:
from sklearn.decomposition import TruncatedSVD

tsvd = TruncatedSVD(n_components=3)
tsvd.fit(X_l2)
print(np.round(tsvd.transform(X_l2), 3))
print(tsvd.singular_values_)

[[ 0.3   -0.173 -0.062]
 [ 0.021  0.044  0.024]
 [ 0.175 -0.043  0.107]
 [ 0.16  -0.038  0.147]
 [ 0.043  0.033  0.131]
 [ 0.06   0.05   0.049]
 [ 0.284  0.591 -0.257]
 [ 0.14   0.074  0.137]
 [ 0.242 -0.087 -0.039]
 [ 0.211 -0.139 -0.089]
 [ 0.115  0.167  0.032]
 [ 0.069  0.09   0.146]
 [ 0.164 -0.021  0.048]
 [ 0.363  0.476  0.21 ]
 [ 0.045  0.035 -0.003]
 [ 0.288 -0.117  0.111]
 [ 0.085  0.084  0.197]
 [ 0.745 -0.002 -0.358]
 [ 0.194  0.37   0.093]
 [ 0.499 -0.253  0.029]
 [ 0.058  0.011 -0.093]
 [ 0.01   0.004  0.034]
 [ 0.069  0.027  0.116]
 [ 0.013  0.026  0.011]
 [ 0.144  0.253  0.126]
 [ 0.404 -0.289 -0.207]
 [ 0.318 -0.231 -0.224]
 [ 0.147  0.246 -0.13 ]
 [ 0.087  0.129  0.054]
 [ 0.216  0.372 -0.047]
 [ 0.086  0.043  0.095]
 [ 0.03   0.034  0.004]
 [ 0.411 -0.249 -0.339]
 [ 0.194 -0.07   0.082]
 [ 0.195  0.356 -0.1  ]
 [ 0.02  -0.001  0.014]
 [ 0.11   0.17   0.034]
 [ 0.041  0.035  0.084]
 [ 0.763 -0.352  0.177]
 [ 0.37  -0.157  0.098]
 [ 0.     0.     0.   ]
 [ 0.376 -0.262 

In [22]:
df_comp = pd.DataFrame(tsvd.components_, columns=vectorizer_l2.get_feature_names())
df_comp = df_comp.apply(lambda x: np.round(x,3))
print(df_comp)

      3g   able  access  account  accurate  actually     ad  addition    ads  \
0  0.007  0.018   0.024    0.010     0.009     0.010  0.007     0.027  0.006   
1  0.011  0.023  -0.006    0.004     0.016     0.008  0.006     0.034  0.006   
2 -0.009 -0.020   0.024    0.043    -0.011     0.023  0.024    -0.007  0.013   

     ago  ...   want    way  weeks   wish   work  world   yeah   year  years  \
0  0.011  ...  0.030  0.037  0.012  0.004  0.024  0.072  0.003  0.034  0.015   
1  0.020  ...  0.044 -0.015  0.022  0.004  0.048 -0.040  0.002 -0.018  0.000   
2  0.010  ...  0.001  0.031 -0.003  0.014 -0.038  0.012  0.010 -0.002  0.016   

     yes  
0  0.025  
1 -0.010  
2  0.017  

[3 rows x 288 columns]


In [23]:
lsi_l2 = LsiModel(corpus=corpus_l2, id2word=id2word_l2, num_topics=3)
lsi_l2.print_topics(3)

[(0,
  '-0.612*"iphone" + -0.402*"phone" + -0.311*"use" + -0.293*"great" + -0.209*"camera" + -0.116*"like" + -0.116*"know" + -0.108*"picture" + -0.105*"easy" + -0.101*"best"'),
 (1,
  '0.528*"great" + 0.503*"camera" + -0.446*"iphone" + 0.222*"picture" + 0.150*"shoot" + 0.147*"point" + -0.139*"phone" + 0.110*"really" + 0.084*"buy" + 0.081*"sd790is"'),
 (2,
  '0.535*"use" + -0.400*"iphone" + -0.371*"great" + 0.285*"easy" + 0.188*"like" + 0.162*"phone" + -0.143*"recommend" + 0.134*"unit" + 0.130*"best" + 0.129*"picture"')]

In [24]:
lsi_l2_docs = lsi_l2[corpus_l2]
for row in lsi_l2_docs:
    print(row)

[(0, -0.30040816701679113), (1, -0.17277639829610014), (2, -0.05604805573746973)]
[(0, -0.021427254668531875), (1, 0.044281807161398), (2, 0.028056348499541143)]
[(0, -0.1750436110767487), (1, -0.04165963614038273), (2, 0.10854033065443337)]
[(0, -0.160272829989145), (1, -0.03998989797450388), (2, 0.15187647645550587)]
[(0, -0.043697710594772274), (1, 0.03071053468837573), (2, 0.1348338844453575)]
[(0, -0.05989107037198155), (1, 0.04933111652545354), (2, 0.053071747964656454)]
[(0, -0.2839842311412281), (1, 0.5897261609170099), (2, -0.25461526334012574)]
[(0, -0.14042760848943037), (1, 0.07416138358114062), (2, 0.13638540752773848)]
[(0, -0.24181807922415502), (1, -0.08535690564471193), (2, -0.03491083377917162)]
[(0, -0.2110289594260443), (1, -0.13830074077324395), (2, -0.08626794491562066)]
[(0, -0.11528015846362188), (1, 0.16581107315852808), (2, 0.032231050813056335)]
[(0, -0.0691664829684536), (1, 0.08950624978607796), (2, 0.1370872809178143)]
[(0, -0.1637311409902305), (1, -0.019

[(0, -0.013197619255568761), (1, 0.005735228342699836), (2, -0.0013727639809173174)]


In [25]:
scores_lsi_l2 = [[np.round(doc[1],3) for doc in row] for row in lsi_l2_docs]
df_lsi_l2 = pd.DataFrame(scores_lsi_l2, columns=['Topic 1', 'Topic 2', 'Topic 3'])
df_lsi_l2

Topic 1  Topic 2  Topic 3
0     -0.300   -0.173   -0.056
1     -0.021    0.044    0.028
2     -0.175   -0.042    0.109
3     -0.160   -0.040    0.152
4     -0.044    0.031    0.135
5     -0.060    0.049    0.053
6     -0.284    0.590   -0.255
7     -0.140    0.074    0.136
8     -0.242   -0.085   -0.035
9     -0.211   -0.138   -0.086
10    -0.115    0.166    0.032
11    -0.069    0.090    0.137
12    -0.164   -0.020    0.038
13    -0.363    0.476    0.207
14    -0.044    0.037    0.003
15    -0.288   -0.117    0.110
16    -0.085    0.084    0.193
17    -0.745   -0.002   -0.357
18    -0.194    0.371    0.091
19    -0.499   -0.253    0.029
20    -0.058    0.011   -0.102
21    -0.010    0.004    0.035
22    -0.069    0.026    0.124
23    -0.013    0.026    0.010
24    -0.143    0.254    0.131
25    -0.404   -0.288   -0.215
26    -0.318   -0.231   -0.218
27    -0.147    0.246   -0.128
28    -0.087    0.129    0.052
29    -0.216    0.372   -0.046
..       ...      ...      ...
205   -0.170   -0.001    0.096
206   -0.038    0.037    0.020
207   -0.016   -0.009   -0.004
208   -0.259   -0.074    0.145
209   -0.306   -0.207   -0.227
210   -0.119    0.249   -0.010
211   -0.004    0.006    0.012
212   -0.346   -0.057    0.389
213   -0.050    0.059    0.039
214   -0.278   -0.172   -0.167
215   -0.271   -0.142   -0.018
216   -0.155   -0.081   -0.077
217   -0.040    0.034    0.058
218   -0.066    0.047    0.114
219   -0.186    0.127    0.267
220   -0.150    0.237   -0.058
221   -0.057    0.009    0.051
222   -0.026    0.014    0.034
223   -0.023    0.008    0.037
224   -0.059    0.051    0.040
225   -0.062    0.034    0.074
226   -0.363   -0.071    0.334
227   -0.181    0.311    0.128
228   -0.151   -0.049    0.070
229   -0.154    0.406   -0.083
230   -0.303   -0.205   -0.155
231   -0.237   -0.019    0.205
232      NaN      NaN      NaN
233   -0.148    0.036    0.259
234   -0.013    0.006   -0.001

[235 rows x 3 columns]

##### Using the SVD approach the topic output seems to produce different results. Based on SVD approach I would have to completely relabel my topics